# For higher environments using nginx reverse proxy
swagger:
  pathMapping: ${SWAGGER_PATH_MAPPING:/api1}

---

# For local environments
spring:
  profiles: local
swagger:
  pathMapping: ${SWAGGER_PATH_MAPPING:/v1}
---